# Generated by Django 4.2 on 2023-04-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('command', models.CharField(choices=[('play', 'play'), ('pause', 'pause'), ('resume', 'resume'), ('stop', 'stop'), ('skip', 'skip'), ('shuffle', 'shuffle'), ('search', 'search')], max_length=10)),
                ('extra', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
