# Generated by Django 4.2 on 2023-04-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandhistory',
            options={'verbose_name_plural': 'Command Histories'},
        ),
    ]
